### PR TITLE
README and fetch.py fix

### PR DESCRIPTION
**Pull request by GojaN**
Hi

Here is the first version of the README and a little fix in fetch.py.
I remove the "Contact me" section of the README until you review it for public access.

fetch.py was fail when the commit comment has a double quote so I escape it. Please check the code to be sure. It's works for me.

### CODE REVIEW

**Comment by GojaN** [comment]
Add the '--allow-empty' fix to this pull request

**Comment by nodirt** [comment]
Merged, finally. Sorry for taking so long. I was really busy.

**Comment by nodirt** [comment]
You can use [this preview](http://github.github.com/github-flavored-markdown/preview.html) to see how the README will look like after your changes. Please, do not commit for this purpose. Commit only after it looks good.

**Comment by GojaN** [comment]
Excellent!
I was looking for something like that to test the readme format.

Don't worry for the delay, i can wait.

I was thinking in give git-tf workitem association support this days. I
really need it in order to continue using git-tf. This seams really easy.
Have you already think about that?

**Comment by nodirt** [comment]
The main reason why I didn't implement clone and workitem (let's call this command as "wi") yet is that some initialization code was ran before running the commands. The initialization included: checks, "cd" to the root dir, switching to the "tfs" branch, etc. But "clone" and "wi" don't need that so I had to refactor code before implementing them.

Now I did it, finally. Here is a description of the d3b8ed9a5b6af7d941569b5964144305d4b7a3e5 commit:

> Each command is a self-sufficient executable that can be ran without
> git-tf. It is done because clone and wi do not need the "init" in
> main.py.
> 
> Now each command is accessible as an executable with name "git-tf-<command>".
> It is a pattern followed by git: any git command is accessible as an executable in
>   /usr/lib/git-core.
> 
> A git-tf-<command> executable is just a symlink to a <command>.py files.

So, now each command runs the initialization itself, and new commands are not required to do that. They can do whatever they want.
Now I will implement "wi" first, and then "clone". Not sure when, though.

It will be great if you try the latest code.

**Comment by GojaN** [comment]
I understand the need of the refactoring, but I was thinking in something more simple for the 'wi' operation. My idea is pass the workitem info in the commit message, something like: "Fix bug (#workitem:12345,98765)", and when checkin parse the message and call 'tf checkin' with the '-associate:" option. [Here](http://msdn.microsoft.com/en-us/library/gg475882.aspx) is a description of this option.

This is a functionality that I find useful to have regardless of the 'git-tf-wi' command.

**Comment by nodirt** [comment]
Yes, I understood "wi" the same. Here is proposed usage:

```
$ git tf wi 12345
Workitem 12345 is associated with commit ab34cd
$ git tf wi 98765
Workitem 98765 is associated with commit ab34cd
```

The workitem numbers will be stored in notes in the tf.wi namespace. Then you push it:

```
$ git tf push
...
Pushing ab34cd...
Associated workitems: 12345, 98765
```

I will implement it very soon because it is easy indeed.

**Comment by nodirt** [comment]
BTW. This pull request is not the best place to discuss workitem association. It is better to do it in a new issue.
But don't open a new issue. I will implement it really soon.

**Pull request closed without merging**
